language: python
python:
  - 2.6
  - 2.7
env:
  - REQUIREMENTS_SUFFIX=
install:
  - sudo apt-get install libxml2-dev libxslt1-dev libcurl3 python-pycurl
  - pip install -r requirements$REQUIREMENTS_SUFFIX.txt --use-mirrors || true
  - pip install -r dev-requirements$REQUIREMENTS_SUFFIX.txt --use-mirrors || true
  - pip install coveralls --use-mirrors  # Required fro coveralls reporting.
  - sudo apt-get install slurm-llnl slurm-llnl-torque # slurm-drmaa1 slurm-drmaa-dev
  - sudo apt-get install libslurm23
  - wget http://launchpadlibrarian.net/104075475/slurm-drmaa1_1.0.4-3_amd64.deb
  - sudo dpkg -i slurm-drmaa1_1.0.4-3_amd64.deb
  - wget http://launchpadlibrarian.net/104075474/slurm-drmaa-dev_1.0.4-3_amd64.deb
  - sudo dpkg -i slurm-drmaa-dev_1.0.4-3_amd64.deb
  - sudo /usr/sbin/create-munge-key
  - sudo service munge start
  - sudo python scripts/configure_test_slurm.py
  - echo "export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so" >> local_env.sh
  - echo ". $VIRTUAL_ENV/bin/activate" >> local_env.sh
  - pip install drmaa 
  - sudo adduser --quiet --disabled-password --gecos TEST u1  ## Create user for run-as-user test.  
#  - sudo apt-get install condor
script: . local_env.sh; pyflakes pulsar test && flake8 --exclude test_tool_deps.py --max-complexity 9 pulsar test && nosetests
after_success:
  - coveralls

## TODO: Figure out why Python 3.3 hangs.
#matrix:
#  include:
#    - python: 3.3
#      env: REQUIREMENTS_SUFFIX=3
#  allow_failures:
#    - python: 3.3     
